apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: auth-platform
data:
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
  KC_DB_USERNAME: keycloak
  KC_HOSTNAME: auth.local
  KC_HTTP_ENABLED: "true"
  KC_PROXY: edge
  KEYCLOAK_ADMIN: admin
